// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.Game = (function() {

    function Game(root) {
      this.root = root;
      this.updateView = __bind(this.updateView, this);

      this.update = __bind(this.update, this);

      this.feedPet = __bind(this.feedPet, this);

      this.run = __bind(this.run, this);

      this.world = new World();
      this.loveBar = $("#love-bar");
      this.hungerBar = $("#hunger-bar");
    }

    Game.prototype.run = function() {
      this.pet = new Creature(this);
      this.world.addCreature(this.pet);
      return this.update();
    };

    Game.prototype.feedPet = function(food) {
      return this.pet.eat(food.value);
    };

    Game.prototype.update = function() {
      this.world.update();
      return this.root.setTimeout(this.update, 500);
    };

    Game.prototype.updateView = function(pet) {
      if (pet === this.pet) {
        this.loveBar.css({
          width: "" + pet.happiness + "%"
        });
        return this.hungerBar.css({
          width: "" + pet.hunger + "%"
        });
      }
    };

    return Game;

  })();

}).call(this);
