// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.World = (function() {

    function World() {
      this.update = __bind(this.update, this);

      this.addCreature = __bind(this.addCreature, this);
      this.creatures = [];
    }

    World.prototype.addCreature = function(c) {
      return this.creatures.push(c);
    };

    World.prototype.update = function() {
      var c, _i, _len, _ref, _results;
      _ref = this.creatures;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        _results.push(c.update());
      }
      return _results;
    };

    return World;

  })();

}).call(this);
